<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-03-09 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
=======
# Generated by Django 4.1.7 on 2023-05-21 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import item.models
>>>>>>> 4fdda5b4a658ec79584c478eb3ae25454cf1a038


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('destinations', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='item_images')),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('max_persons', models.CharField(blank=True, max_length=50, null=True)),
                ('pool', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('persons', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('places', models.BooleanField(default=False)),
                ('restaurants', models.BooleanField(default=False)),
                ('vacations', models.BooleanField(default=False)),
                ('activities', models.BooleanField(default=False)),
                ('trip', models.BooleanField(default=False)),
                ('start_date', models.DateField(default=False)),
                ('end_date', models.DateField(default=False)),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='item.city')),
=======
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                (
                    "city",
                    models.CharField(max_length=255, verbose_name=item.models.City),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "destinations",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.FloatField()),
                (
                    "images",
                    models.ImageField(blank=True, null=True, upload_to="item_images"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("type", models.CharField(blank=True, max_length=150, null=True)),
                ("max_persons", models.CharField(blank=True, max_length=50, null=True)),
                ("pool", models.BooleanField(default=False)),
                ("food", models.BooleanField(default=False)),
                ("parking", models.BooleanField(default=False)),
                ("bedrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("bathrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("persons", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "published_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
>>>>>>> 4fdda5b4a658ec79584c478eb3ae25454cf1a038
            ],
        ),
    ]
