# Generated by Django 4.1.7 on 2023-04-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_alter_item_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
    ]
